import JSZip from 'jszip'

export interface DetectedField {
  id: string
  label: string
  placeholder: string
  required: boolean
  /** Original shape name from PPTX for future text injection */
  shapeName: string
  /** Placeholder type from PPTX (title, body, subTitle, ctrTitle, etc.) */
  phType: string | null
  /** Tri-state: admin controls whether employees can/must fill this field */
  editable_state: 'locked' | 'optional' | 'required'
  /** Shape position on slide as percentage (0-100) for thumbnail highlighting */
  bounds?: { x: number; y: number; w: number; h: number }
}

/**
 * Placeholder types to skip — these are auto-generated by PowerPoint, not user-editable content.
 */
const SKIP_PH_TYPES = new Set(['sldNum', 'dt', 'ftr', 'hdr'])

/**
 * Human-readable labels for common PowerPoint placeholder types.
 */
const PH_TYPE_LABELS: Record<string, string> = {
  title: 'Title',
  ctrTitle: 'Title',
  subTitle: 'Subtitle',
  body: 'Body Text',
}

/**
 * Extract text from all <a:t> elements within an XML string segment.
 */
function extractText(xml: string): string {
  const parts: string[] = []
  for (const m of xml.matchAll(/<a:t[^>]*>([^<]*)<\/a:t>/g)) {
    parts.push(m[1])
  }
  return parts.join('').trim()
}

/**
 * Parse a single slide XML to detect text placeholders.
 * Returns an array of detected fields for shapes that contain editable text.
 */
function parseSlideXml(slideXml: string): DetectedField[] {
  const fields: DetectedField[] = []

  // Match each shape <p:sp>...</p:sp>
  const spRegex = /<p:sp\b[^>]*>[\s\S]*?<\/p:sp>/g
  for (const spMatch of slideXml.matchAll(spRegex)) {
    const sp = spMatch[0]

    // Must have a text body
    if (!sp.includes('<p:txBody>') && !sp.includes('<p:txBody ')) continue

    // Skip freehand / custom-geometry shapes (ink drawings, connectors, etc.)
    if (sp.includes('<a:custGeom')) continue

    // Extract shape name from <p:cNvPr name="...">
    const nameMatch = sp.match(/<p:cNvPr[^>]+name="([^"]*)"/)
    const shapeName = nameMatch?.[1] ?? ''

    // Check for placeholder element <p:ph type="..." idx="...">
    const phMatch = sp.match(/<p:ph[^>]*\/>/)
    let phType: string | null = null

    if (phMatch) {
      const typeMatch = phMatch[0].match(/type="([^"]*)"/)
      phType = typeMatch?.[1] ?? null
    }

    // Skip non-editable placeholder types (slide number, date, footer, header)
    if (phType && SKIP_PH_TYPES.has(phType)) continue

    // Extract shape position (EMU units → percentage of slide)
    // Standard 16:9 slide: 12192000 x 6858000 EMU
    const offMatch = sp.match(/<a:off\s+x="(\d+)"\s+y="(\d+)"/)
    const extMatch = sp.match(/<a:ext\s+cx="(\d+)"\s+cy="(\d+)"/)
    let bounds: { x: number; y: number; w: number; h: number } | undefined
    if (offMatch && extMatch) {
      const slideW = 12192000
      const slideH = 6858000
      bounds = {
        x: (parseInt(offMatch[1]) / slideW) * 100,
        y: (parseInt(offMatch[2]) / slideH) * 100,
        w: (parseInt(extMatch[1]) / slideW) * 100,
        h: (parseInt(extMatch[2]) / slideH) * 100,
      }
    }

    // Extract text content
    const text = extractText(sp)

    // Skip shapes with no text body content and no placeholder type
    // (likely decorative shapes or images)
    if (!phType && !text) continue

    // Skip very long text (likely paragraphs, not editable fields)
    if (text.length > 300) continue

    // Determine label
    let label = ''
    if (phType && PH_TYPE_LABELS[phType]) {
      label = PH_TYPE_LABELS[phType]
    } else if (shapeName && !shapeName.match(/^(TextBox|Rectangle|Shape)\s*\d*$/i)) {
      // Use shape name if it's meaningful (not generic like "TextBox 1")
      label = shapeName
    } else if (text) {
      // Use first 50 chars of existing text as label
      label = text.length > 50 ? text.slice(0, 50) + '…' : text
    } else {
      label = 'Text Field'
    }

    fields.push({
      id: crypto.randomUUID(),
      label,
      placeholder: text,
      required: false,
      shapeName,
      phType,
      editable_state: 'locked',
      bounds,
    })
  }

  return fields
}

/**
 * Parse a PPTX file and extract text placeholders for a specific page.
 * Uses the actual slide order from presentation.xml, not file names.
 *
 * @param file - The PPTX File object
 * @param pageIndex - Zero-based page index
 * @returns Array of detected editable fields
 */
export async function parsePptxFields(file: File, pageIndex: number): Promise<DetectedField[]> {
  const zip = await JSZip.loadAsync(file)

  // Read presentation.xml.rels for rId → target mapping
  const presRelsFile = zip.file('ppt/_rels/presentation.xml.rels')
  if (!presRelsFile) return []
  const presRelsXml = await presRelsFile.async('string')

  const ridToTarget = new Map<string, string>()
  for (const m of presRelsXml.matchAll(
    /<Relationship[^>]+Id="(rId\d+)"[^>]+Target="([^"]+)"[^>]*\/>/g
  )) {
    ridToTarget.set(m[1], m[2])
  }

  // Read presentation.xml for slide order
  const presFile = zip.file('ppt/presentation.xml')
  if (!presFile) return []
  const presXml = await presFile.async('string')

  const orderedSlideTargets: string[] = []
  for (const m of presXml.matchAll(/<p:sldId[^>]+r:id="(rId\d+)"[^>]*\/>/g)) {
    const target = ridToTarget.get(m[1])
    if (target) orderedSlideTargets.push(target)
  }

  if (pageIndex >= orderedSlideTargets.length) return []

  // Get the slide file for this page
  const slideTarget = orderedSlideTargets[pageIndex]
  // Target is relative to ppt/ (e.g., "slides/slide1.xml")
  const slidePath = slideTarget.startsWith('/') ? `ppt${slideTarget}` : `ppt/${slideTarget}`

  const slideFile = zip.file(slidePath)
  if (!slideFile) return []

  const slideXml = await slideFile.async('string')
  return parseSlideXml(slideXml)
}
